### PR TITLE
Add Addresses section

### PR DESCRIPTION
**Pull request by rukku**

### CODE REVIEW

**Comment by mr-mig** [comment]
Thanks for contributing! 👍 
I would still call it "Addresses". WDYT?

**Comment by rukku** [comment]
Point taken. Was actually thinking of adding a geospatial section but I
don't have the links to the articles yet. Addresses it is. Will just put a
new PR by then. :)

**Comment by mr-mig** [comment]
Thank you again!

**Comment by rukku** [comment]
Thanks for starting this project, too :D

**Pull request merged**
