### PR TITLE
Create Spanish Translation

### PR DESCRIPTION
**Pull request by eamanu**
I Think that is important have the same information in different languages, because the most of developer that will read this repo, maybe is new in programming. And if you have to read some things that you don`t know good and in different language, this complicate the whole things.

### CODE REVIEW

**Comment by mr-mig** [comment]
I think this is a great idea! 
Thanks for taking time to translate it. 

There are 2 problems I see:
1. All the translations need to keep up with the main repo
2. Most materials are still available only in English 

Do you think it's a worthy time investment to maintain it? 
Do you think it's not a misservice for novice people to give them a set of links which will still lead to English materials?

**Comment by eamanu** [comment]
Hello @mr-mig 

Sorry for the delay of my response.

Yes you are right with the two problems that you see. The first, need support to maintain the repo updating, again the problem now is found peoples that could reviewing your repo and then making the translation. 

The second problem, I could resolve it searching materials in Spanish (there is a lot of materials in spanish)

I think that if we have repos in different languages this will help to novice people, because not all people can study english (I am from Argentina), and you spend lot of time trying to read something written in a different language than your native language. Furthermore, we could have more kids that can start to code before go to University

My solution is make a different repo in my Github, and have the spanish version there. Obviously, making reference to your repo how mother.

**Comment by mr-mig** [comment]
I would say having a separate repo is a good idea 👍 
You can maintain your own fork in Spanish. 

I can reference your fork in the main repo so that it is discoverable.

**Comment by mr-mig** [comment]
@eamanu ping me back please when you have a repo with Spanish materials

**Pull request closed without merging**
