### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by LewisVo**
this is essential for every open source project, either with or without codes. This is just a suggestion, you may opt for another license if you like.

### CODE REVIEW

**Comment by aycgit** [comment]
I dont think licences are applicable for documents

**Comment by eamanu** [comment]
I dont think that @mr-mig want to license this repo beacuse is a links´ compendium.

**Comment by LewisVo** [comment]
@aycgit  @eamanu  It's definitely up to him. But thinking that this repo doesn't need or doesn't deserve a license is is terrible. Licensing a project, either consisting of codes or just plain documentation, is practical. If you don't believe me, see these projects:  
- https://github.com/vitalysim/Awesome-Hacking-Resources
- https://github.com/yangshun/tech-interview-handbook
- https://github.com/mbeaudru/modern-js-cheatsheet 
- ....

**Comment by eamanu** [comment]
Ok, You are right @LewisVo. I am not expert in licenses but, those are documents licenses or software code licenses? Or is the same? Is your commit a standard license (e.g. GNU-GPL, MIT, ...)? I think that is more appropriate something like this: https://en.wikipedia.org/wiki/GNU_Free_Documentation_License, is not it?

**Comment by LewisVo** [comment]
@eamanu For non-software license, MIT is not the best actually. Please refer here to see some of the most applicable license for non-software project : https://choosealicense.com/non-software.  

So why do I and some others (as mentioned in the link above)  choose MIT,GPL ....?  
1. Because they are popular. If you want to ask more, maybe you should open an issue at these above repo.
2. Because we focus on the content of it. Licensing something with MIT simply implies that this is free (as in freedom and free beer). Want to modify this, copy this, sell this, save for private use -> Go on and do it. But if something goes wrong, dont blame me. Licensing something with GPL tells people hey you are fine to do commerce with this, maybe bring my writing into a book but open source that book.
3. You are right, in the terms of these license, most of them mention "software" but with the context of use on Github, these term should be the same as "project", in my opinion

**Comment by eamanu** [comment]
Very interesting @LewisVo!!!. I like this licence https://choosealicense.com/licenses/cc-by-4.0/

Maybe @mr-mig have to decide wich licence is the correct for the project

**Comment by mr-mig** [comment]
@LewisVo @eamanu thank you for raising the issue. 
I think the best option is actually `CC-BY-4.0`

**Pull request closed without merging**
