### PR TITLE
Added recently published companion to Soft Skills

### PR DESCRIPTION
**Pull request by joshearl**
This book expands on the career stuff from Soft Skills.

### CODE REVIEW

**Comment by mr-mig** [comment]
Thanks for the contribution! 
Did not know that it has been already published. I'd prefer to read it and evaluate first before adding to the list. 
I'll let it hang here for some time 👍

**Comment by joshearl** [comment]
Makes sense! Nice job on this guide.

**Comment by jasondown** [comment]
I second this. Excellent book.

**Comment by kev5** [comment]
Many people forget the importance of soft skills these days. This is a good reminder.

**Comment by mr-mig** [comment]
Thank you for all your comments! 
Adding it right away! 🚀

**Pull request merged**
