### PR TITLE
Add Hyperpolyglot, learnxinyminutes

### PR DESCRIPTION
**Pull request by troglotit**
Hey, Alexey, thank you for work! I read some of your posts, but remembered your "How to FP" guide which starts with POODR 😄. Totally second that 👍. 

I found learnxinyminutes really useful for me to get started quickly.
Hyperpolyglot is still useful, but maybe it's too specific.

I totally support that this list is **curated**, so feel free to decline or propose changes. 

As you can see, I added sentence which describes what it is about, but then found nothing had anything like that. And also, I didn't know at which category it belongs to, so I created **Languages** section.

### CODE REVIEW

**Comment by mr-mig** [comment]
Hey, @troglotit! 
Nice to hear that my stuff is actually useful 😊 

Those are quite interesting additions. 
I'd ask you to make a couple of changes before merging:

- [ ] Use description format from **Falsehoods** section, so that the text is under the link and indented 
- [ ] Move link to the **Practices** section.  
I am hesitant to add new generic sections as they will potentially grow infinitely

**Comment by shubham893000** [comment]
I'm a beginner here can you help me please

**Comment by mr-mig** [comment]
@shubham893000 how can we help?

**Comment by troglotit** [comment]
Moved to another section, and indented. Couldn't think of any emoji 😅.

**Comment by mr-mig** [comment]
Thank you for your effort and contribution 💪

**Pull request merged**
