### PR TITLE
adding some problem solving resources

### PR DESCRIPTION
**Pull request by Guilhermeslucas**
Adding fix about #42 .

### CODE REVIEW

**Comment by mr-mig** [comment]
Why are there so many of those books? 
Can you recommend one or two? 
Which one is "absolutely must read"? 

The whole purpose of having a repo is to *simplify* finding great resources, without the need to *filter* through those. 
Have a look at [Contribution Guidelines](https://github.com/mr-mig/every-programmer-should-know/blob/master/CONTRIBUTING.md) for some details.

**Comment by Guilhermeslucas** [comment]
You have a point! I'll list the two best books of the list!

**Comment by Guilhermeslucas** [comment]
I tried to choose the best ones, don't know if you agree!

**Comment by mr-mig** [comment]
Gonna merge it, thx for adding!

**Pull request merged**
